apiVersion: canary.company.io/v1alpha1
kind: RouteRolloutPlan
metadata:
  name: payments-api-plan
spec:
  appName: payments-api
  stableDeployment: payments-api-primary
  canaryDeployment: payments-api
  stableService: payments-api-primary
  canaryService: payments-api
  routeName: payments-api
  namespace: team-a
  minCanaryReplicas: 1
  safetyExtraReplicas: 0
  steps:
    - name: step-00-preview
      canaryWeight: 0
      stableWeight: 100
      canaryReplicas: auto
      approvalRequired: true

    - name: step-10
      canaryWeight: 10
      stableWeight: 90
      canaryReplicas: auto
      approvalRequired: true

    - name: step-25
      canaryWeight: 25
      stableWeight: 75
      canaryReplicas: auto
      approvalRequired: true

    - name: step-50
      canaryWeight: 50
      stableWeight: 50
      canaryReplicas: auto
      approvalRequired: true

    - name: step-100-canary
      canaryWeight: 100
      stableWeight: 0
      canaryReplicas: auto
      approvalRequired: true
