namespace: team-a
serviceName: payments-api
servicePort: 80
targetPort: 8080
canary:
  enabled: true
  suspend: false
  skipAnalysis: false
  revertOnDeletion: true
analysis:
  interval: 1m
  threshold: 32
  stepWeight: 10
  maxWeight: 50
manualGate:
  url: http://manual-gate-webhook.canary-system.svc.cluster.local:8082/v1/flagger/hooks/manual-gate
manualRollback:
  url: http://manual-gate-webhook.canary-system.svc.cluster.local:8082/v1/flagger/hooks/manual-rollback
smoke:
  enabled: true
  url: http://smoke-runner.team-a.svc.cluster.local/v1/smoke
previewIngress:
  enabled: true
  className: nginx
  host: payments-preview.internal.company.com
  officeCidrs:
    - 10.20.0.0/16
    - 10.30.0.0/16
  expireAt: "2026-12-31T23:59:59Z"
