apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: approval-api
  template:
    metadata:
      labels:
        app: approval-api
    spec:
      containers:
        - name: approval-api
          image: {{ .Values.approvalApi.image }}
          ports:
            - containerPort: {{ .Values.approvalApi.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: approval-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: approval-api
  ports:
    - port: {{ .Values.approvalApi.port }}
      targetPort: {{ .Values.approvalApi.port }}
